### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [matianfu/FUNK#1]
I would like to point out that an identifier like "[`__FUNK_C_H_`](https://github.com/matianfu/FUNK/blob/3f77a9ae2f1ed461a0e5845404e98cc133d51868/src/funk.h#L1)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by matianfu** [comment]
Thank you. Will be fixed in next push. :)

**Comment by matianfu** [comment]
Fixed in new release. Tag v0.08. SHA-1: 64f0bed.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/matianfu/FUNK/commit/8b38c6f410b5288c6e580a68e85bc4a9e6d0ea93#diff-0be071d7990b608a8ae5ec79b684e70dL1).
